### ISSUE TITLE
Some question about the version of Animatediff used in experiments

### ISSUE THREAD

**Issue by shaoshitong** [PKU-YuanGroup/ChronoMagic-Bench#3]
![image](https://github.com/user-attachments/assets/88e02505-18b8-4870-9640-e8ba50b33093)

Hello, I would like to ask this side of the Modelscope T2V and Animatediff are what version, is it sd v1.5 v2 or v3 version, or based on sd-xl build?

**Comment by SHYuanBest** [comment]
Thank you for your interest! Both Modelscope T2V and Animatediff use sd v1.5, which are the latest official releases. Details about the models are provided in the appendix of our paper, feel free to have a look.
