### ISSUE TITLE
contrast-img

### ISSUE THREAD

**Issue by pkuhxy** [PKU-YuanGroup/ChronoMagic-Bench#9]
![0](https://github.com/user-attachments/assets/c43e6ce7-8334-4af0-8b9c-d1ac2e10b2a9)
![1](https://github.com/user-attachments/assets/a0b147ec-5d4b-4d53-830d-9e3b57fb93e2)
![2](https://github.com/user-attachments/assets/c587d46c-1a55-4ef4-9aca-44c37292eed7)
![3](https://github.com/user-attachments/assets/7715212b-b048-47d2-8238-d31fe921b689)
![4](https://github.com/user-attachments/assets/a96efd56-30fa-411b-858f-ef9a14c0fc43)
![5](https://github.com/user-attachments/assets/f43a8ba6-cfad-4d4e-a362-58edf1fbaf87)
![6](https://github.com/user-attachments/assets/43a1449c-6c36-463e-83b1-c4ad69331bc6)
![7](https://github.com/user-attachments/assets/38c376fa-cdce-4cbb-bef6-845477936353)

**Comment by SHYuanBest** [comment]
![model_pipeline_2](https://github.com/user-attachments/assets/c23b207f-96ff-4b94-9ea5-d385ed65c477)

**Comment by SHYuanBest** [comment]
https://github.com/user-attachments/assets/e4e3e519-95d4-44e0-afa7-9a833f99e090


https://github.com/user-attachments/assets/93e9a8b8-c427-4b8c-8982-74fb9146ca62


https://github.com/user-attachments/assets/aa68cbbc-1112-448e-9736-a03d9182f47f

![1](https://github.com/user-attachments/assets/7d912d9d-26bb-424f-ab8a-7adabe098d9e)

**Comment by SHYuanBest** [comment]
![model_pipeline](https://github.com/user-attachments/assets/eecc8ae9-9921-4ead-93bc-88035c506b19)

**Comment by SHYuanBest** [comment]
![Image](https://github.com/user-attachments/assets/f9a1dc9b-befb-44ee-8a4d-cef89e717dde)
